### ISSUE TITLE
Upload to S3 with the right headers

### ISSUE THREAD

**Issue by lologhi** [KonstantinKuklin/AsseticStaticGzipBundle#5]
Hello,
Following this [Gist](https://gist.github.com/lologhi/e022bd15eb705ac8d50c), I'm pushing my (prod env) assets directly to my S3. But as S3 can't manage on the fly gzip, I'd like to **only** push gzipped version of my assets. Any idea how I could do that ?
Thx !

**Comment by KonstantinKuklin** [comment]
Hi, it is not the case to use current library.
That is why you will not find how to configure such behavior.
But if you will remove https://github.com/KonstantinKuklin/AsseticStaticGzipBundle/blob/master/Command/DumpCommand.php#L46 you will get expected functionality

**Comment by lologhi** [comment]
Thx a lot for the help!
